// Auto-generated by scripts/build-guide-index.mjs
// DO NOT EDIT MANUALLY - run: node scripts/build-guide-index.mjs

export interface GuideSearchEntry {
  id: string
  title: string
  keywords: string
  category: string
  url: string
  source: 'guide'
}

export const GUIDE_ENTRIES_EN: GuideSearchEntry[] = [
  {
    "id": "guide-docs-hub",
    "title": "Hub",
    "keywords": "hub guide documentation readme",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/README.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-overview",
    "title": "Overview",
    "keywords": "overview guide documentation guide overview",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/00-overview.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-getting-started",
    "title": "Getting Started",
    "keywords": "getting started guide documentation guide getting started",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/01-getting-started.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-capabilities",
    "title": "Capabilities",
    "keywords": "capabilities guide documentation guide capabilities",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/02-capabilities.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-security",
    "title": "Security",
    "keywords": "security guide documentation guide security",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/03-security.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-troubleshooting",
    "title": "Troubleshooting",
    "keywords": "troubleshooting guide documentation guide troubleshooting",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/04-troubleshooting.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-cheatsheet",
    "title": "Cheatsheet",
    "keywords": "cheatsheet guide documentation reference cheatsheet",
    "category": "Reference",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/reference/cheatsheet.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-faq",
    "title": "FAQ",
    "keywords": "faq guide documentation reference faq",
    "category": "Reference",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/reference/faq.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-comparison",
    "title": "Comparison",
    "keywords": "comparison guide documentation reference comparison",
    "category": "Reference",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/reference/comparison.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-glossary",
    "title": "Glossary",
    "keywords": "glossary guide documentation reference glossary",
    "category": "Reference",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/reference/glossary.md",
    "source": "guide"
  },
  {
    "id": "guide-prompts-file-ops",
    "title": "File Ops",
    "keywords": "file ops prompts prompts file ops",
    "category": "Prompts",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/prompts/file-ops.md",
    "source": "guide"
  },
  {
    "id": "guide-prompts-document-creation",
    "title": "Document Creation",
    "keywords": "document creation prompts prompts document creation",
    "category": "Prompts",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/prompts/document-creation.md",
    "source": "guide"
  },
  {
    "id": "guide-prompts-data-extraction",
    "title": "Data Extraction",
    "keywords": "data extraction prompts prompts data extraction",
    "category": "Prompts",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/prompts/data-extraction.md",
    "source": "guide"
  },
  {
    "id": "guide-prompts-research",
    "title": "Research",
    "keywords": "research prompts prompts research",
    "category": "Prompts",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/prompts/research.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-client-followup-tracker",
    "title": "Client Followup Tracker",
    "keywords": "client followup tracker workflows workflows client followup tracker",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/client-followup-tracker.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-competitor-analysis",
    "title": "Competitor Analysis",
    "keywords": "competitor analysis workflows workflows competitor analysis",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/competitor-analysis.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-compliance-checklist",
    "title": "Compliance Checklist",
    "keywords": "compliance checklist workflows workflows compliance checklist",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/compliance-checklist.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-email-templates",
    "title": "Email Templates",
    "keywords": "email templates workflows workflows email templates",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/email-templates.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-expense-tracking",
    "title": "Expense Tracking",
    "keywords": "expense tracking workflows workflows expense tracking",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/expense-tracking.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-file-organization",
    "title": "File Organization",
    "keywords": "file organization workflows workflows file organization",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/file-organization.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-inventory-tracking",
    "title": "Inventory Tracking",
    "keywords": "inventory tracking workflows workflows inventory tracking",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/inventory-tracking.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-invoice-generation",
    "title": "Invoice Generation",
    "keywords": "invoice generation workflows workflows invoice generation",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/invoice-generation.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-knowledge-transfer",
    "title": "Knowledge Transfer",
    "keywords": "knowledge transfer workflows workflows knowledge transfer",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/knowledge-transfer.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-meeting-prep",
    "title": "Meeting Prep",
    "keywords": "meeting prep workflows workflows meeting prep",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/meeting-prep.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-newsletter-creation",
    "title": "Newsletter Creation",
    "keywords": "newsletter creation workflows workflows newsletter creation",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/newsletter-creation.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-payment-reminders",
    "title": "Payment Reminders",
    "keywords": "payment reminders workflows workflows payment reminders",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/payment-reminders.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-presentation-slides",
    "title": "Presentation Slides",
    "keywords": "presentation slides workflows workflows presentation slides",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/presentation-slides.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-price-comparison",
    "title": "Price Comparison",
    "keywords": "price comparison workflows workflows price comparison",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/price-comparison.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-project-planning",
    "title": "Project Planning",
    "keywords": "project planning workflows workflows project planning",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/project-planning.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-prospect-research",
    "title": "Prospect Research",
    "keywords": "prospect research workflows workflows prospect research",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/prospect-research.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-quality-checklist",
    "title": "Quality Checklist",
    "keywords": "quality checklist workflows workflows quality checklist",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/quality-checklist.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-quote-creation",
    "title": "Quote Creation",
    "keywords": "quote creation workflows workflows quote creation",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/quote-creation.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-quote-to-invoice",
    "title": "Quote To Invoice",
    "keywords": "quote to invoice workflows workflows quote invoice",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/quote-to-invoice.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-report-synthesis",
    "title": "Report Synthesis",
    "keywords": "report synthesis workflows workflows report synthesis",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/report-synthesis.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-review-response",
    "title": "Review Response",
    "keywords": "review response workflows workflows review response",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/review-response.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-social-media-posts",
    "title": "Social Media Posts",
    "keywords": "social media posts workflows workflows social media posts",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/social-media-posts.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-supplier-order",
    "title": "Supplier Order",
    "keywords": "supplier order workflows workflows supplier order",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/supplier-order.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-team-handoff",
    "title": "Team Handoff",
    "keywords": "team handoff workflows workflows team handoff",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/team-handoff.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-website-audit",
    "title": "Website Audit",
    "keywords": "website audit workflows workflows website audit",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/website-audit.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-work-log",
    "title": "Work Log",
    "keywords": "work log workflows workflows work log",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/work-log.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-scheduled-automation",
    "title": "Scheduled Automation",
    "keywords": "scheduled automation daily brief weekly report monthly dashboard recurring on-demand planned tasks",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/scheduled-automation.en.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-memory-setup",
    "title": "Cross-Session Memory",
    "keywords": "memory session persistence memory.md desktop commander context cross-session",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/memory-setup.en.md",
    "source": "guide"
  },
  {
    "id": "guide-capabilities-customize-tab",
    "title": "Customize Tab & Skills",
    "keywords": "customize tab skills slash commands pdf xlsx docx mcp connector plugins personalization",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/02-capabilities.md#customize-cowork",
    "source": "guide"
  },
  {
    "id": "guide-capabilities-desktop-commander",
    "title": "Desktop Commander",
    "keywords": "desktop commander extension file access memory mcp server install one-click",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/01-getting-started.md#step-8-install-desktop-commander-recommended",
    "source": "guide"
  },
  {
    "id": "guide-capabilities-sonnet-model",
    "title": "Model Selection (Sonnet 4.6)",
    "keywords": "model selection sonnet opus agentic cost performance osworld benchmark",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/02-capabilities.md#model-selection",
    "source": "guide"
  }
]

export const GUIDE_ENTRIES_FR: GuideSearchEntry[] = [
  {
    "id": "guide-docs-hub",
    "title": "Hub",
    "keywords": "hub guide documentation readme",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/README.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-overview",
    "title": "Overview",
    "keywords": "overview guide documentation guide overview",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/00-overview.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-getting-started",
    "title": "Getting Started",
    "keywords": "getting started guide documentation guide getting started",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/01-getting-started.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-capabilities",
    "title": "Capabilities",
    "keywords": "capabilities guide documentation guide capabilities",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/02-capabilities.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-security",
    "title": "Security",
    "keywords": "security guide documentation guide security",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/03-security.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-troubleshooting",
    "title": "Troubleshooting",
    "keywords": "troubleshooting guide documentation guide troubleshooting",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/04-troubleshooting.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-cheatsheet",
    "title": "Cheatsheet",
    "keywords": "cheatsheet guide documentation reference cheatsheet",
    "category": "Référence",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/reference/cheatsheet.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-faq",
    "title": "FAQ",
    "keywords": "faq guide documentation reference faq",
    "category": "Référence",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/reference/faq.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-comparison",
    "title": "Comparison",
    "keywords": "comparison guide documentation reference comparison",
    "category": "Référence",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/reference/comparison.md",
    "source": "guide"
  },
  {
    "id": "guide-docs-glossary",
    "title": "Glossary",
    "keywords": "glossary guide documentation reference glossary",
    "category": "Référence",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/reference/glossary.md",
    "source": "guide"
  },
  {
    "id": "guide-prompts-file-ops",
    "title": "File Ops",
    "keywords": "file ops prompts prompts file ops",
    "category": "Prompts",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/prompts/file-ops.md",
    "source": "guide"
  },
  {
    "id": "guide-prompts-document-creation",
    "title": "Document Creation",
    "keywords": "document creation prompts prompts document creation",
    "category": "Prompts",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/prompts/document-creation.md",
    "source": "guide"
  },
  {
    "id": "guide-prompts-data-extraction",
    "title": "Data Extraction",
    "keywords": "data extraction prompts prompts data extraction",
    "category": "Prompts",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/prompts/data-extraction.md",
    "source": "guide"
  },
  {
    "id": "guide-prompts-research",
    "title": "Research",
    "keywords": "research prompts prompts research",
    "category": "Prompts",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/prompts/research.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-client-followup-tracker",
    "title": "Client Followup Tracker",
    "keywords": "client followup tracker workflows workflows client followup tracker",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/client-followup-tracker.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-competitor-analysis",
    "title": "Competitor Analysis",
    "keywords": "competitor analysis workflows workflows competitor analysis",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/competitor-analysis.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-compliance-checklist",
    "title": "Compliance Checklist",
    "keywords": "compliance checklist workflows workflows compliance checklist",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/compliance-checklist.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-email-templates",
    "title": "Email Templates",
    "keywords": "email templates workflows workflows email templates",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/email-templates.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-expense-tracking",
    "title": "Expense Tracking",
    "keywords": "expense tracking workflows workflows expense tracking",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/expense-tracking.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-file-organization",
    "title": "File Organization",
    "keywords": "file organization workflows workflows file organization",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/file-organization.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-inventory-tracking",
    "title": "Inventory Tracking",
    "keywords": "inventory tracking workflows workflows inventory tracking",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/inventory-tracking.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-invoice-generation",
    "title": "Invoice Generation",
    "keywords": "invoice generation workflows workflows invoice generation",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/invoice-generation.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-knowledge-transfer",
    "title": "Knowledge Transfer",
    "keywords": "knowledge transfer workflows workflows knowledge transfer",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/knowledge-transfer.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-meeting-prep",
    "title": "Meeting Prep",
    "keywords": "meeting prep workflows workflows meeting prep",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/meeting-prep.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-newsletter-creation",
    "title": "Newsletter Creation",
    "keywords": "newsletter creation workflows workflows newsletter creation",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/newsletter-creation.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-payment-reminders",
    "title": "Payment Reminders",
    "keywords": "payment reminders workflows workflows payment reminders",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/payment-reminders.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-presentation-slides",
    "title": "Presentation Slides",
    "keywords": "presentation slides workflows workflows presentation slides",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/presentation-slides.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-price-comparison",
    "title": "Price Comparison",
    "keywords": "price comparison workflows workflows price comparison",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/price-comparison.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-project-planning",
    "title": "Project Planning",
    "keywords": "project planning workflows workflows project planning",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/project-planning.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-prospect-research",
    "title": "Prospect Research",
    "keywords": "prospect research workflows workflows prospect research",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/prospect-research.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-quality-checklist",
    "title": "Quality Checklist",
    "keywords": "quality checklist workflows workflows quality checklist",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/quality-checklist.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-quote-creation",
    "title": "Quote Creation",
    "keywords": "quote creation workflows workflows quote creation",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/quote-creation.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-quote-to-invoice",
    "title": "Quote To Invoice",
    "keywords": "quote to invoice workflows workflows quote invoice",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/quote-to-invoice.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-report-synthesis",
    "title": "Report Synthesis",
    "keywords": "report synthesis workflows workflows report synthesis",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/report-synthesis.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-review-response",
    "title": "Review Response",
    "keywords": "review response workflows workflows review response",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/review-response.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-social-media-posts",
    "title": "Social Media Posts",
    "keywords": "social media posts workflows workflows social media posts",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/social-media-posts.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-supplier-order",
    "title": "Supplier Order",
    "keywords": "supplier order workflows workflows supplier order",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/supplier-order.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-team-handoff",
    "title": "Team Handoff",
    "keywords": "team handoff workflows workflows team handoff",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/team-handoff.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-website-audit",
    "title": "Website Audit",
    "keywords": "website audit workflows workflows website audit",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/website-audit.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-work-log",
    "title": "Work Log",
    "keywords": "work log workflows workflows work log",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/work-log.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-scheduled-automation-fr",
    "title": "Automatisation Planifiée",
    "keywords": "automatisation planifiée brief quotidien rapport hebdomadaire dashboard mensuel récurrent à la demande tâches planifiées",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/scheduled-automation.md",
    "source": "guide"
  },
  {
    "id": "guide-workflows-memory-setup-fr",
    "title": "Mémoire Inter-Sessions",
    "keywords": "mémoire sessions persistance memory.md desktop commander contexte inter-sessions",
    "category": "Workflows",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/workflows/memory-setup.md",
    "source": "guide"
  },
  {
    "id": "guide-capabilities-customize-tab-fr",
    "title": "Onglet Personnaliser & Skills",
    "keywords": "personnaliser onglet skills commandes slash pdf xlsx docx connecteur mcp plugins",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/02-capabilities.fr.md#personnaliser-cowork",
    "source": "guide"
  },
  {
    "id": "guide-capabilities-desktop-commander-fr",
    "title": "Desktop Commander",
    "keywords": "desktop commander extension accès fichiers mémoire serveur mcp installation",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/01-getting-started.fr.md#étape-8--installer-desktop-commander-recommandé",
    "source": "guide"
  },
  {
    "id": "guide-capabilities-sonnet-model-fr",
    "title": "Sélection du Modèle (Sonnet 4.6)",
    "keywords": "modèle sélection sonnet opus agentique coût performance benchmark par défaut",
    "category": "Guide",
    "url": "https://github.com/FlorianBruniaux/claude-cowork-guide/blob/main/guide/02-capabilities.fr.md#sélection-du-modèle",
    "source": "guide"
  }
]
